lexica = {"meta": "to a large extent based on https://en.oxforddictionaries.com/thesaurus/cause",
 "lexicon": {
   "causation": {
     "bring",
     "brought",
     "cause",
     "create",
     "effect",
     "elicit",
     "evoke",
     "foster"
     "generate",
     "incite",
     "induce",
     "introduce",
     "lead",
     "led",
     "originate",
     "produce",
     "prompt",
     "provoke",
     "result",
     "rise",
     "risen",
     "rose",
     "spark",
     "trigger"},
   "improvement": {
     "ameliorate",
     "better",
     "boost",
     "enhance",
     "help",
     "improve",
     "improvement",
     "promote",
     "refine",
     "respond"},
   "worsening": {
     "augment",
     "compound",
     "degenerate",
     "deteriorate",
     "exacerbate",
     "intensify",
     "weaken",
     "worse",
     "worsen"},
   "administration": {
     "administer",
     "for",
     "require",
     "requiring",
     "s/p",
     "start",
     "undergo",
     "undergone",
     "underwent",
     "with"},
   "non-administration": {
     "avoid",
     "neither",
     "not",
     "stop"},
   "revealing": {
     "clear",
     "demonstrate",
     "detect",
     "display",
     "exhibit",
     "indicate",
     "manifest",
     "reveal",
     "see",
     "seen",
     "show",
     "uncover",
     "view"},
   "carrying-out": {
     "carried",
     "carry",
     "complete",
     "conduct",
     "evaluate",
     "execute",
     "implement",
     "perform",
     "test"}
 }
}